### ISSUE TITLE
Поменять ссылку

### ISSUE THREAD

**Issue by modvala** [demidovakatya/vvedenie-mashinnoe-obuchenie#10]
Ссылка поехала в курсе Analytic Edge
правильная ссылка: https://www.edx.org/course/analytics-edge-mitx-15-071x-2

**Comment by demidovakatya** [comment]
@modvala большое спасибо, [пофиксила](https://github.com/demidovakatya/vvedenie-mashinnoe-obuchenie/commit/5525853dcbe8adc0b31f6433ccec4f60c6386d58)
