### ISSUE TITLE
Несколько дополнений к порядку просмотра

### ISSUE THREAD

**Issue by YehudaItkin** [demidovakatya/vvedenie-mashinnoe-obuchenie#13]
Первое - может быть неплохая идея добавить в твой список ЛикБеза по машинному обучению лекции Воронцова в Яндексе. Они весьма параллельны специализации, но подробнее в смысле математики.
И второе - курс Mining massive datasets существует в виде МООКА - https://lagunita.stanford.edu/courses/course-v1:ComputerScience+MMDS+Fall2016/about

**Comment by demidovakatya** [comment]
- [ ] лекции Воронцова в Яндексе
- [x] курс Mining massive datasets существует в виде МООКА (https://github.com/demidovakatya/vvedenie-mashinnoe-obuchenie/commit/bfec78478a33bd155f982148e21040012ed52e52)

**Comment by demidovakatya** [comment]
- [x] лекции Воронцова в Яндексе (https://github.com/demidovakatya/vvedenie-mashinnoe-obuchenie/commit/b59f636036154b82ad4a0936e4d58e43fb205923)
- [x] курс Mining massive datasets существует в виде МООКА (https://github.com/demidovakatya/vvedenie-mashinnoe-obuchenie/commit/bfec78478a33bd155f982148e21040012ed52e52)
