### ISSUE TITLE
Invalid link

### ISSUE THREAD

**Issue by vadimostanin** [demidovakatya/vvedenie-mashinnoe-obuchenie#23]
Link "Machine Learning Resource Guide" that leads to "https://www.dropbox.com/s/z4f9oer4nkyu9tf/MachineLearningResourceGuide.pdf"
is invalid

**Comment by ex00** [comment]
+
Машинное обучение — Петер Флах (pdf)
https://www.dropbox.com/s/wkmoxtq0egzcoxc/Flach_P_Machine_Learning_RU.pdf
actual: 404

**Comment by demidovakatya** [comment]
@vadimostanin 
fixed: 415116b

@ex00 
fixed: 14ed00e
