### ISSUE TITLE
Порядок просмотра курсов

### ISSUE THREAD

**Issue by ne3x7** [demidovakatya/vvedenie-mashinnoe-obuchenie#8]
От самого введения к Ветрову

**Comment by demidovakatya** [comment]
@ne3x7 кароч сложно с этим :с

запилила [такой вот пост](http://cotique.me/blog/ml-spec-recommendations), похоже на правду?

**Comment by YehudaItkin** [comment]
Может быть неплохая идея добавить в твой список ЛикБеза по машинному обучению лекции Воронцова в Яндексе. Они весьма параллельны специализации, но подробнее в смысле математики.
